<?php
/*
Version History:
  1.0.0 (2017-02-12)
    1) Moved this into its own class out of XML_Sitemap
*/
class RobotsTxt extends Base
{
    const VERSION = '1.0.0';
    const CRAWL_DELAY = 2;

    private $txt = '';

    public function draw()
    {
        $this->setup();
        $this->getHeader();
        $this->getBody();
        header('Content-Type: text/plain');
        return $this->txt;
    }

    private function getHeader()
    {
        $this->txt.=
             "# Robots.txt file for "
            .$this->vars['textEnglish']." [".$this->vars['URL']."]\n"
            ."# Generated by ".System::get_item_version('system_family')
            ." ".System::get_item_version('codebase').".".$this->vars['db_version']."\n"
            .($this->vars['archive'] ? "# This site is ARCHIVED and should NOT be indexed\n" : "")
            ."\n";
    }

    private function getBody()
    {
        if ($this->vars['archive']) {
            $this->txt.=
                 "User-agent: *\n"
                ."Disallow: ".BASE_PATH."\n";
            return;
        }
        $this->txt.=
             "User-agent: *\n"
            ."Disallow: ".BASE_PATH."ajax/\n"
            ."Disallow: ".BASE_PATH."cron/\n"
            ."Disallow: ".BASE_PATH."css/\n"
            ."Disallow: ".BASE_PATH."export/\n"
            ."Disallow: ".BASE_PATH."facebook/\n"
            ."Disallow: ".BASE_PATH."img/\n"
            ."Disallow: ".BASE_PATH."java/\n"
            ."Disallow: ".BASE_PATH."osd/\n"
            ."Disallow: ".BASE_PATH."sysjs/\n"
            ."Disallow: ".BASE_PATH."UserFiles/File/\n"
            ."Disallow: ".BASE_PATH."UserFiles/Media/\n"
            ."Disallow: ".BASE_PATH."UserFiles/Video/\n"
            ."Sitemap: ".trim($this->vars['URL'], '/')."/sitemap.xml\n"
            ."\n"
            ."User-agent: Googlebot\n"
            ."Crawl-delay: ".static::CRAWL_DELAY."\n"
            ."Disallow: ".BASE_PATH."*?*\n"
            ."Disallow: ".BASE_PATH."*?*\n"
            ."\n"
            ."User-agent: Yahoo! Slurp\n"
            ."Crawl-delay: ".static::CRAWL_DELAY."\n"
            ."Disallow: ".BASE_PATH."*?*\n"
            ."Disallow: ".BASE_PATH."*?*\n"
            ."\n"
            ."User-agent: msnbot\n"
            ."Crawl-delay: ".static::CRAWL_DELAY."\n"
            ."Disallow: ".BASE_PATH."*?*\n"
            ."Disallow: ".BASE_PATH."*?*\n";
    }

    private function setup()
    {
        global $system_vars;
        $this->vars = $system_vars;
        if (!$this->vars) {
            die('RobotsTxt Error: No site with ID '.SYS_ID);
        }
    }
}
